#!/bin/bash

# Travis CI
if [[ "$TRAVIS" != true ]]; then
  echo "Invalid TRAVIS";
  exit 1;
fi

if [[ -z "$TRAVIS_BUILD_NUMBER" ]]; then
  echo "Missing TRAVIS_BUILD_NUMBER";
  exit 1;
fi

if [[ ! "$TRAVIS_JOB_NUMBER" =~ ^[0-9]+\.1$ ]]; then
  echo "Invalid TRAVIS_JOB_NUMBER";
  exit 0;
fi

if [[ "$TRAVIS_PULL_REQUEST" != false ]]; then
  echo "Invalid TRAVIS_PULL_REQUEST";
  exit 0;
fi

# Artifact
if [[ -z "$ARTIFACT_NAME" ]]; then
  echo "Missing ARTIFACT_NAME";
  exit 1;
fi

ARTIFACT_FILE=$(find build/libs/ -maxdepth 1 -type f -iname "$ARTIFACT_NAME" | head -n 1);
if [[ -z "$ARTIFACT_FILE" ]]; then
  echo "Missing ARTIFACT_FILE";
  exit 1;
fi

# SpongePowered/Ore
if [[ -z "$ORE_KEY" ]]; then
  echo "Missing ORE_KEY";
  exit 1;
fi

if [[ -z "$ORE_RECOMMENDED" ]]; then
  echo "Missing ORE_RECOMMENDED";
  exit 1;
fi

if [[ "$ORE_RECOMMENDED" != true ]] && [[ "$ORE_RECOMMENDED" != false ]]; then
  echo "Invalid ORE_RECOMMENDED";
  exit 1;
fi

if [[ -z "$ORE_CREATE_FORUM_POST" ]]; then
  echo "Missing ORE_CREATE_FORUM_POST";
  exit 1;
elif [[ "$ORE_CREATE_FORUM_POST" != false ]] && [[ "$ORE_CREATE_FORUM_POST" != true ]]; then
  echo "Invalid ORE_CREATE_FORUM_POST";
  exit 1;
fi

if [[ -z "$ORE_DESCRIPTION" ]]; then
  echo "Missing ORE_DESCRIPTION";
  exit 1;
fi

if [[ -z "$ORE_CHANNEL" ]]; then
  echo "Missing ORE_CHANNEL";
  exit 1;
fi

if [[ -z "$ORE_PLUGIN_ID" ]]; then
  echo "Missing ORE_PLUGIN_ID";
  exit 1;
fi

function request() {
  local response=$(curl --silent --write-out "\n%{http_code}" "$@");
  local body=$(echo "$response" | head -n -1);
  local status=$(echo "$response" | tail -n 1);

  # 200 OK, 201 Created, 204 No Content
  if [[ "$status" == 200 ]] || [[ "$status" == 201 ]] || [[ "$status" == 204 ]]; then
    echo "$body";
    return 0;
  fi

  echo "Invalid response: $body ($status)"
  if [[ "$status" =~ "^[0-9]+$" ]]; then
    return $status;
  fi

  return -1;
}

# SpongePowered/Ore - Authenticate
echo "Requesting Session Token...";
ORE_SESSION=$(request \
--request "POST" \
--header "Authorization: OreApi apikey=$ORE_KEY" \
--form "fake=false" \
"https://ore.stage.spongemc.org/api/v2/authenticate");
if [[ -z "$ORE_SESSION" ]]; then
  exit 1;
fi

echo "Extracting Session Token...";
ORE_SESSION_KEY=$(echo "$ORE_SESSION" | jq --raw-output ".session");
if [[ -z "$ORE_SESSION_KEY" ]]; then
  echo "Missing ORE_SESSION_KEY";
  exit 1;
fi

ORE_PLUGIN_INFO_TAGS=$(jq --null-input --compact-output --raw-output \
--arg key0 "Channel" \
--arg value0 "$ORE_CHANNEL" \
'. | .[$key0]=$value0');
if [[ -z "$ORE_PLUGIN_INFO_TAGS" ]]; then
  echo "Missing ORE_PLUGIN_INFO_TAGS";
  exit 1;
fi

ORE_PLUGIN_INFO=$(jq --null-input --compact-output --raw-output \
--arg key0 "recommended" \
--argjson value0 "$ORE_RECOMMENDED" \
--arg key1 "create_forum_post" \
--argjson value1 "$ORE_CREATE_FORUM_POST" \
--arg key2 "description" \
--arg value2 "$ORE_DESCRIPTION" \
--arg key3 "tags" \
--argjson value3 "$ORE_PLUGIN_INFO_TAGS" \
'. | .[$key0]=$value0 | .[$key1]=$value1 | .[$key2]=$value2 | .[$key3]=$value3');
if [[ -z "$ORE_PLUGIN_INFO" ]]; then
  echo "Missing ORE_PLUGIN_INFO";
  exit 1;
fi

# SpongePowered/Ore - Deploy Version
echo "Uploading $ARTIFACT_FILE...";
ORE_VERSION=$(request \
--request "POST" \
--header "Authorization: OreApi session=$ORE_SESSION_KEY" \
--form "plugin-info=$ORE_PLUGIN_INFO" \
--form "plugin-file=@$ARTIFACT_FILE" \
"https://ore.stage.spongemc.org/api/v2/projects/$ORE_PLUGIN_ID/versions");
if [[ -z "$ORE_VERSION" ]]; then
  exit 1;
fi

echo "$ORE_VERSION";
exit 0;